from my_bot import MyBot
import discord


class Reminder:
    CONTENT = "content"
    DELAY = "delay"
    NEXT_TIMESTAMP = "next"
    CHANNEL_ID = "channel_id"
    TIMES = "times"
    ID = "id"

    def __init__(
            self,
            bot: MyBot,
            content: str,
            delay: list[int, int, int, int],
            channel: discord.TextChannel,
            username: str,
            times: int,
            id_: str,
            next_timestamp: float
    ):
        self.bot: MyBot = ...
        self.content: str = ...
        self.delay: list[int, int, int, int] = ...
        self.username: str = ...
        self.id: str = ...
        self.next_timestamp: float = ...
        self.channel: discord.TextChannel = ...
        self.times: int = ...
    ...
    def set_next_timestamp(self) -> None:...
    def decrement_times(self) -> None:...

def reminder_codename_gen(rem: Reminder) -> str:...
