from my_bot import MyBot


class Poll:
    def __init__(self,
                 bot: MyBot,
                 answers: list[str],
                 choices: list[int, int],
                 timestamp: float,
                 votes: dict[int, list[str]] = None,
                 poll_id: str = None,
                 message: str = None
    ):
        self.poll_id: str = ...
        self.bot: MyBot = ...
        self.answers: list[str] = ...
        self.choices: list[int, int] = ...
        self.timestamp: float = ...
        self.votes: dict[int, list[str]] = ...
        ...