from typing import TypeVar, Collection, Callable

_T = TypeVar("_T")
_U = TypeVar("_U")

def find(iterable: Collection[_T], fn: Callable[[_T], bool]) -> int:...
def map(iterable: Collection[_T], fn: Callable[[_T], _U]) -> list[_U]:...
async def async_map(iterable: Collection[_T], fn: Callable[[_T], _U]) -> list[_U]:...