from typing import Optional

import discord

from .bot_data import BotStateManager
from .volatile_storage import VolatileStorage
from .warning_system import WarningSystem


class MyBot(discord.Bot):
    instance: MyBot = ...

    def __init__(self, *args:..., **kwargs:...):
        self.__data: BotStateManager = ...
        self.__warning_system: WarningSystem = ...
        self.__session: VolatileStorage = ...

    @property
    def data(self) -> BotStateManager:...
    @property
    def warnings(self) -> WarningSystem:...
    @property
    def session(self) -> VolatileStorage:...
    @staticmethod
    def get_instance() -> MyBot:...

    async def get_or_fetch_channel(self, _id: int) -> Optional[discord.abc.GuildChannel]:...
    async def get_or_fetch_message(self, channel_id: int, message_id: int) -> Optional[discord.Message]:...
    async def is_user_a_member(self, guild: discord.Guild , user: discord.User) -> Optional[discord.Member]:...